sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
env:
  - GRADLE_VERSION=3.4.1
before_script:
  - mkdir -p $ANDROID_HOME/licenses
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
  - wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
  - unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
  - export PATH=~/gradle/gradle-$GRADLE_VERSION/bin:$PATH
