language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-26
env:
  - GRADLE_VERSION=5.1.1 HTTPBIN=httpbin.bemisc.com
before_script:
  - wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
  - unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
  - export PATH=~/gradle/gradle-$GRADLE_VERSION/bin:$PATH
  - touch local.properties
