sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.1.3
    - android-25
env:
  - GRADLE_VERSION=3.4.1
before_script:
  - wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
  - sudo unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
  - export PATH=$PATH:~/gradle/gradle-$GRADLE_VERSION/bin
