name: Build Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
          unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
          touch local.properties
        env:
          GRADLE_VERSION: 5.1.1
      - name: Build packages
        run: |
          export PATH=~/gradle/gradle-$GRADLE_VERSION/bin:$PATH
          HTTPBIN=httpbin.bemisc.com gradle
        env:
          GRADLE_VERSION: 5.1.1
