name: Build Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        java-version: [8]
        gradle-version: [6.7.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
          unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
          touch local.properties
        env:
          GRADLE_VERSION: ${{ matrix.gradle-version }}
      - name: Build packages
        run: |
          export PATH=~/gradle/gradle-$GRADLE_VERSION/bin:$PATH
          HTTPBIN=httpbin.bemisc.com gradle
        env:
          GRADLE_VERSION: ${{ matrix.gradle-version }}
