name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        java-version: [11, 13, 15, 16, 17, 18]
        gradle-version: [7.4, 7.5, 7.6]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
          unzip -q -d ~/gradle gradle-$GRADLE_VERSION-bin.zip
          touch local.properties
          echo "~/gradle/gradle-$GRADLE_VERSION/bin" >> $GITHUB_PATH
        env:
          GRADLE_VERSION: ${{ matrix.gradle-version }}
      - name: Build packages
        run: HTTPBIN=httpbin.bemisc.com gradle
      - name: Test packages
        run: HTTPBIN=httpbin.bemisc.com gradle test --info
